export const imagePresets = [
  {
    id: "instagram-square",
    name: "Instagram Square",
    platform: "Instagram",
    width: 1080,
    height: 1080,
    aspectRatio: "1:1",
  },
  {
    id: "instagram-portrait",
    name: "Instagram Portrait",
    platform: "Instagram",
    width: 1080,
    height: 1350,
    aspectRatio: "4:5",
  },
  {
    id: "instagram-story",
    name: "Instagram Story",
    platform: "Instagram",
    width: 1080,
    height: 1920,
    aspectRatio: "9:16",
  },
  {
    id: "facebook-post",
    name: "Facebook Post",
    platform: "Facebook",
    width: 1200,
    height: 630,
    aspectRatio: "1.91:1",
  },
  {
    id: "linkedin-post",
    name: "LinkedIn Post",
    platform: "LinkedIn",
    width: 1200,
    height: 627,
    aspectRatio: "1.91:1",
  },
  {
    id: "youtube-thumbnail",
    name: "YouTube Thumbnail",
    platform: "YouTube",
    width: 1280,
    height: 720,
    aspectRatio: "16:9",
  },
  {
    id: "website-hero",
    name: "Website Hero",
    platform: "Website",
    width: 1600,
    height: 900,
    aspectRatio: "16:9",
  },
  {
    id: "website-social",
    name: "Website Social Preview",
    platform: "Website",
    width: 1200,
    height: 630,
    aspectRatio: "1.91:1",
  },
];